name: mpd_client
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  chopper: ^8.0.0
  logger: ^2.4.0
  flutter_bloc: ^8.1.6
  logging: ^1.2.0
  media_kit: ^1.1.10                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4
  equatable: ^2.0.5
  dio: ^5.5.0+1
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  pretty_dio_logger: ^1.3.1
  formz: ^0.7.0
  uuid: ^4.4.2
  go_router: ^14.2.1
  local_auth: ^2.2.0
  image_painter: ^0.7.1
  lottie: ^3.1.2
  pretty_chopper_logger: ^1.0.11
  date_picker_plus: ^4.1.0
  image_picker: ^1.1.2
  mask_text_input_formatter: ^2.9.0
  pinput: ^5.0.0
  shimmer: ^3.0.0
  circle_flags: ^5.0.0
  qr_flutter: ^4.1.0
  flutter_screenutil: ^5.9.3
  custom_refresh_indicator: ^4.0.1
  pinch_to_zoom_scrollable: ^0.1.2
  visibility_detector: ^0.4.0+2
  open_app_file: ^4.0.2
  path: ^1.9.0
  file_picker: ^8.0.0+1
  video_player: ^2.9.1
  video_thumbnail: ^0.5.3
  flutter_image_compress: ^2.3.0
  video_compress: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_annotation: ^4.9.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  chopper_generator: ^8.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/anim/

  fonts:
    - family: Gilroy Light
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
    - family: Gilroy Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
    - family: Gilroy Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
