name: mpd_client
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flutter_localizations:
    sdk: flutter
  flutter_animate: ^4.5.0
  flutter_svg: ^2.0.10+1
  chopper: ^7.0.6
  logger: ^2.4.0
  flutter_bloc: ^8.1.6
  logging: ^1.2.0
  media_kit: ^1.1.10                             # Primary package.
  media_kit_video: ^1.2.4                        # For video rendering.
  media_kit_libs_video: ^1.0.4
  equatable: ^2.0.5
  dio: ^5.5.0+1
  shared_preferences: ^2.2.3
  get_it: ^7.7.0
  pretty_dio_logger: ^1.3.1
  formz: ^0.7.0
  uuid: ^4.4.2
  go_router: ^14.2.1
  local_auth: ^2.2.0
  image_painter: ^0.7.1
  lottie: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  json_annotation: ^4.9.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/images/
    - assets/anim/

  fonts:
    - family: Gilroy Light
      fonts:
        - asset: assets/fonts/Gilroy-Light.ttf
    - family: Gilroy Regular
      fonts:
        - asset: assets/fonts/Gilroy-Regular.ttf
    - family: Gilroy Medium
      fonts:
        - asset: assets/fonts/Gilroy-Medium.ttf
